
services:
  app:
    container_name: unique_beauty_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app              # Live code updates
      - /app/node_modules   # Prevent conflicts between local & container deps
      - /app/.next          # Avoid caching issues
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/unique_beauty_studio
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: unique_beauty_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: unique_beauty_studio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: